all:
  children:
    prod:
      vars:
        github_account: chriszal
      hosts:
        my-host:
          ansible_host: 34.77.144.200
          # apps must have the same name as the corresponding Github repo
          apps:
            - referenceLetterApp
            - referenceLetterAppPanel