---
- hosts: all
  become: yes
  become_user: deploy
  tasks:
  # - name: Deploy apps
  #   command: "/home/deploy/deploy-{{ item }}.sh"
  #   loop: "{{ apps }}"
    - name: Change branch
      command: "git checkout dockerize"
      args:
        chdir: "/home/deploy/{{apps[0]}}"

    - name: Pull latest updates
      command: "git pull"
      args:
        chdir: "/home/deploy/{{item}}"
      loop: "{{ apps }}"

      #push to docker hub
      #docker build -t chriszal/referral .  
      #docker push chriszal/referral:latest 


      #move to folders for backend and delete yamls

      #apply new yamls
      
      #populate database
      