all:
  children:
    prod:
      vars:
        github_account: chriszal
        docker_username: chriszal
        docker_password: # TODO add your ENCRYPTED Docker Hub password here
      hosts:
        my-host:
          ansible_host: 35.241.238.99
          # apps must have the same name as the corresponding Github repo
          apps:
            - referenceLetterApp
            - referenceLetterAppPanel
